# Generated by Django 5.2.2 on 2025-06-06 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at', 'updated_at']},
        ),
        migrations.AlterModelTable(
            name='post',
            table='testing_posts',
        ),
    ]
