# Generated by Django 5.2.2 on 2025-06-06 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_alter_post_options_alter_post_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at', 'updated_at'], 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('title', 'user_email')},
        ),
    ]
