# Generated by Django 5.2.2 on 2025-06-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_alter_post_options_alter_post_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['title', 'user_email'], name='testing_pos_title_f17c8f_idx'),
        ),
    ]
